name: Upload MiniGamesBox-Classic artifact
on:
  push:
    branches:
      - master
    paths:
      - 'MiniGamesBox Classic/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
  pull_request:
    types:
      - closed
    paths:
      - 'MiniGamesBox Classic/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build MiniGamesBox-Classic with ShadowJar
        run: ./gradlew :MiniGamesBox-Classic:shadowJar

      - name: Upload MiniGamesBox-Classic Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiniGamesBox-Classic
          path: MiniGamesBox Classic/build/libs/*-all.jar
